/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-08-01 18:17:36
 */


#include <BCDS_Basics.h>
#include <BCDS_Retcode.h>
#include <BCDS_Environmental.h>
#include <string.h>
#include <inttypes.h>
#include <BCDS_LightSensor.h>
#include <XdkSensorHandle.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include "BusGPIOTest.h"
#include "ConnectivityADCAdc.h"
#include "SensorEnvironment.h"
#include "ConnectivityMQTTMqtt.h"
#include "SensorLight.h"
#include "MitaExceptions.h"
#include "application.h"

#ifndef BCDS_MODULE_ID
#define BCDS_MODULE_ID 0xCAFE
#endif

int32_t ts = 0;
int32_t ones = 0;
bool reading = false;
int32_t pos = 1;
uint32_t val = 0;

Retcode_T initGlobalVariables_application() {
	Retcode_T exception = RETCODE_OK;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	if(exception != NO_EXCEPTION) return exception;
	
	return exception;
}

Retcode_T HandleEvery20Millisecond1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	ts++;
	exception = read_bbb(NULL);
	if(exception != NO_EXCEPTION) return exception;
	if(((ts % 50) == 0) && (ts > 500))
	{
		printf("%s\n", "sensor reading and sending");
		uint32_t sensorLightModalityPreparation_1;
		exception = LightSensor_readLuxData(xdkLightSensor_MAX44009_Handle, &sensorLightModalityPreparation_1);
		if(exception != NO_EXCEPTION) return exception;
		
		char result1953116887_buf[11] = {0};
		char *result1953116887 = result1953116887_buf;
		
		char IfStatement15Result1953116887_2_buf[11] = {0};
		snprintf(IfStatement15Result1953116887_2_buf, sizeof(IfStatement15Result1953116887_2_buf), "%" PRIu32 "", sensorLightModalityPreparation_1);
		memcpy(result1953116887, IfStatement15Result1953116887_2_buf, sizeof(IfStatement15Result1953116887_2_buf));
		
		char* _newConnectivityMQTTMqtt_Light_1 = result1953116887;
		exception = ConnectivityMQTTMqtt_Light_Write(&_newConnectivityMQTTMqtt_Light_1);
		if(exception != NO_EXCEPTION) return exception;
		Environmental_Data_T sensorEnvironmentModalityPreparation_2;
		exception = Environmental_readData(xdkEnvironmental_BME280_Handle, &sensorEnvironmentModalityPreparation_2);
		if(exception != NO_EXCEPTION) return exception;
		
		char result1948293463_buf[12] = {0};
		char *result1948293463 = result1948293463_buf;
		
		char IfStatement15Result1948293463_3_buf[12] = {0};
		snprintf(IfStatement15Result1948293463_3_buf, sizeof(IfStatement15Result1948293463_3_buf), "%" PRId32 "", sensorEnvironmentModalityPreparation_2.temperature);
		memcpy(result1948293463, IfStatement15Result1948293463_3_buf, sizeof(IfStatement15Result1948293463_3_buf));
		
		char* _newConnectivityMQTTMqtt_Temp_2 = result1948293463;
		exception = ConnectivityMQTTMqtt_Temp_Write(&_newConnectivityMQTTMqtt_Temp_2);
		if(exception != NO_EXCEPTION) return exception;
		char result440448608_buf[11] = {0};
		char *result440448608 = result440448608_buf;
		
		char IfStatement15Result440448608_4_buf[11] = {0};
		snprintf(IfStatement15Result440448608_4_buf, sizeof(IfStatement15Result440448608_4_buf), "%" PRIu32 "", sensorEnvironmentModalityPreparation_2.pressure);
		memcpy(result440448608, IfStatement15Result440448608_4_buf, sizeof(IfStatement15Result440448608_4_buf));
		
		char* _newConnectivityMQTTMqtt_Pres_3 = result440448608;
		exception = ConnectivityMQTTMqtt_Pres_Write(&_newConnectivityMQTTMqtt_Pres_3);
		if(exception != NO_EXCEPTION) return exception;
		char result616149297_buf[11] = {0};
		char *result616149297 = result616149297_buf;
		
		char IfStatement15Result616149297_5_buf[11] = {0};
		snprintf(IfStatement15Result616149297_5_buf, sizeof(IfStatement15Result616149297_5_buf), "%" PRIu32 "", sensorEnvironmentModalityPreparation_2.humidity);
		memcpy(result616149297, IfStatement15Result616149297_5_buf, sizeof(IfStatement15Result616149297_5_buf));
		
		char* _newConnectivityMQTTMqtt_Humi_4 = result616149297;
		exception = ConnectivityMQTTMqtt_Humi_Write(&_newConnectivityMQTTMqtt_Humi_4);
		if(exception != NO_EXCEPTION) return exception;
		uint16_t result424866803;
		exception = ConnectivityADCAdc_O2_Read(&result424866803);
		if(exception != NO_EXCEPTION) return exception;
		
		char result2125569871_buf[6] = {0};
		char *result2125569871 = result2125569871_buf;
		
		char IfStatement15Result2125569871_7_buf[6] = {0};
		snprintf(IfStatement15Result2125569871_7_buf, sizeof(IfStatement15Result2125569871_7_buf), "%" PRIu16 "", result424866803);
		memcpy(result2125569871, IfStatement15Result2125569871_7_buf, sizeof(IfStatement15Result2125569871_7_buf));
		
		char* _newConnectivityMQTTMqtt_O2_6 = result2125569871;
		exception = ConnectivityMQTTMqtt_O2_Write(&_newConnectivityMQTTMqtt_O2_6);
		if(exception != NO_EXCEPTION) return exception;
	}


	return NO_EXCEPTION;
}

Retcode_T read_bbb(void* _result)
{

	Retcode_T exception = NO_EXCEPTION;
	
	
	bool result1167129305;
	exception = BusGPIOTest_Inp_Read(&result1167129305);
	if(exception != NO_EXCEPTION) return exception;
	
	bool iv = result1167129305;
	if(iv)
	{
		ones++;
	}
	else
	{
		ones = 0;
	}
	
	if(reading == true)
	{
		if(iv)
		{
			val += 1 << pos;
		}
		
		pos++;
	}
	
	if(pos == 32)
	{
		printf("raw: %" PRIu32 "\n", val);
		int32_t tag = val % 16;
		val /= 16;
		printf("tag: %" PRId32 " val: %" PRIu32 "\n", tag, val);
		if(tag == 3)
		{
			char result753578725_buf[11] = {0};
			char *result753578725 = result753578725_buf;
			
			char IfStatement4Result753578725_5_buf[11] = {0};
			snprintf(IfStatement4Result753578725_5_buf, sizeof(IfStatement4Result753578725_5_buf), "%" PRIu32 "", val);
			memcpy(result753578725, IfStatement4Result753578725_5_buf, sizeof(IfStatement4Result753578725_5_buf));
			
			char* _newConnectivityMQTTMqtt_Tvoc_2 = result753578725;
			exception = ConnectivityMQTTMqtt_Tvoc_Write(&_newConnectivityMQTTMqtt_Tvoc_2);
			if(exception != NO_EXCEPTION) return exception;
		}
		else if(tag == 4)
		{
			char result982006915_buf[11] = {0};
			char *result982006915 = result982006915_buf;
			
			char ConditionalStatement4Result982006915_6_buf[11] = {0};
			snprintf(ConditionalStatement4Result982006915_6_buf, sizeof(ConditionalStatement4Result982006915_6_buf), "%" PRIu32 "", val);
			memcpy(result982006915, ConditionalStatement4Result982006915_6_buf, sizeof(ConditionalStatement4Result982006915_6_buf));
			
			char* _newConnectivityMQTTMqtt_Co2_3 = result982006915;
			exception = ConnectivityMQTTMqtt_Co2_Write(&_newConnectivityMQTTMqtt_Co2_3);
			if(exception != NO_EXCEPTION) return exception;
		}
		else if(tag == 5)
		{
			char result982957246_buf[11] = {0};
			char *result982957246 = result982957246_buf;
			
			char ConditionalStatement4Result982957246_7_buf[11] = {0};
			snprintf(ConditionalStatement4Result982957246_7_buf, sizeof(ConditionalStatement4Result982957246_7_buf), "%" PRIu32 "", val);
			memcpy(result982957246, ConditionalStatement4Result982957246_7_buf, sizeof(ConditionalStatement4Result982957246_7_buf));
			
			char* _newConnectivityMQTTMqtt_Mc10_4 = result982957246;
			exception = ConnectivityMQTTMqtt_Mc10_Write(&_newConnectivityMQTTMqtt_Mc10_4);
			if(exception != NO_EXCEPTION) return exception;
		}
		else if(tag == 6)
		{
			char result734908065_buf[11] = {0};
			char *result734908065 = result734908065_buf;
			
			char ConditionalStatement4Result734908065_8_buf[11] = {0};
			snprintf(ConditionalStatement4Result734908065_8_buf, sizeof(ConditionalStatement4Result734908065_8_buf), "%" PRIu32 "", val);
			memcpy(result734908065, ConditionalStatement4Result734908065_8_buf, sizeof(ConditionalStatement4Result734908065_8_buf));
			
			char* _newConnectivityMQTTMqtt_Mc25_5 = result734908065;
			exception = ConnectivityMQTTMqtt_Mc25_Write(&_newConnectivityMQTTMqtt_Mc25_5);
			if(exception != NO_EXCEPTION) return exception;
		}
		else if(tag == 7)
		{
			char result1978609552_buf[11] = {0};
			char *result1978609552 = result1978609552_buf;
			
			char ConditionalStatement4Result1978609552_9_buf[11] = {0};
			snprintf(ConditionalStatement4Result1978609552_9_buf, sizeof(ConditionalStatement4Result1978609552_9_buf), "%" PRIu32 "", val);
			memcpy(result1978609552, ConditionalStatement4Result1978609552_9_buf, sizeof(ConditionalStatement4Result1978609552_9_buf));
			
			char* _newConnectivityMQTTMqtt_Mc40_6 = result1978609552;
			exception = ConnectivityMQTTMqtt_Mc40_Write(&_newConnectivityMQTTMqtt_Mc40_6);
			if(exception != NO_EXCEPTION) return exception;
		}
		else if(tag == 8)
		{
			char result875339657_buf[11] = {0};
			char *result875339657 = result875339657_buf;
			
			char ConditionalStatement4Result875339657_10_buf[11] = {0};
			snprintf(ConditionalStatement4Result875339657_10_buf, sizeof(ConditionalStatement4Result875339657_10_buf), "%" PRIu32 "", val);
			memcpy(result875339657, ConditionalStatement4Result875339657_10_buf, sizeof(ConditionalStatement4Result875339657_10_buf));
			
			char* _newConnectivityMQTTMqtt_Mc100_7 = result875339657;
			exception = ConnectivityMQTTMqtt_Mc100_Write(&_newConnectivityMQTTMqtt_Mc100_7);
			if(exception != NO_EXCEPTION) return exception;
		}
		else if(tag == 9)
		{
			char result1513835080_buf[11] = {0};
			char *result1513835080 = result1513835080_buf;
			
			char ConditionalStatement4Result1513835080_11_buf[11] = {0};
			snprintf(ConditionalStatement4Result1513835080_11_buf, sizeof(ConditionalStatement4Result1513835080_11_buf), "%" PRIu32 "", val);
			memcpy(result1513835080, ConditionalStatement4Result1513835080_11_buf, sizeof(ConditionalStatement4Result1513835080_11_buf));
			
			char* _newConnectivityMQTTMqtt_Partical_s_8 = result1513835080;
			exception = ConnectivityMQTTMqtt_Partical_s_Write(&_newConnectivityMQTTMqtt_Partical_s_8);
			if(exception != NO_EXCEPTION) return exception;
		}
		
		val = 0;
		pos = 0;
		ones = 0;
		reading = false;
	}
	
	if(ones == 8)
	{
		reading = true;
	}

	return exception;
}


