/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-08-01 18:17:36
 */


#ifndef BUSGPIO_GPIO_H
#define BUSGPIO_GPIO_H

#include <stdbool.h>
#include <BCDS_Retcode.h>


/**
 * Sets up the GPIO.
 */
Retcode_T BusGPIOTest_Setup(void);

/**
 * Enables the GPIO sensor.
 */
Retcode_T BusGPIOTest_Enable(void);

/**
 * Provides read access to inp.
 */
Retcode_T BusGPIOTest_Inp_Read(bool* result);

/**
 * Provides write access to inp.
 */
Retcode_T BusGPIOTest_Inp_Write(bool* result);


#endif
