/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-08-01 18:17:36
 */


#ifndef CONNECTIVITYWLAN_WLAN_H
#define CONNECTIVITYWLAN_WLAN_H

#include <BCDS_Retcode.h>


/**
 * Sets up the WLAN.
 */
Retcode_T ConnectivityWLANNet_Setup(void);

/**
 * Enables the WLAN sensor.
 */
Retcode_T ConnectivityWLANNet_Enable(void);



#endif
