/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-08-01 18:17:36
 */


#include <FreeRTOS.h>
#include <stdint.h>
#include <AdcCentral.h>
#include <Mcu_Adc.h>
#include <BSP_Adc.h>
#include <semphr.h>
#include <BCDS_Retcode.h>
#include "MitaExceptions.h"

static uint16_t AdcResultBuffer = 0;
static SemaphoreHandle_t AdcSampleSemaphore = NULL;

static void adcCallback(ADC_T adc, uint16_t* buffer) {
	BCDS_UNUSED(adc);
	BCDS_UNUSED(buffer);

	BaseType_t higherPriorityTaskWoken = pdFALSE;

	if (pdTRUE == xSemaphoreGiveFromISR(AdcSampleSemaphore, &higherPriorityTaskWoken))
	{
		portYIELD_FROM_ISR(higherPriorityTaskWoken);
	}
	else
	{
		/* ignore... semaphore has already been given */
	}
}

AdcCentral_ConfigSingle_T o2_config = {
	.AcqTime = ADC_ACQ_TIME_16,
	.Appcallback = adcCallback,
	.BufferPtr = &AdcResultBuffer,
	.Channel = ADC_ENABLE_CH5,
	.Reference = ADC_REF_2V5,
	.Resolution = ADC_RESOLUTION_12BIT
};


Retcode_T ConnectivityADCAdc_Setup(void)
{
	Retcode_T exception = RETCODE_OK;
	
	exception = AdcCentral_Init();
	if(exception != RETCODE_OK) return exception;
	
	AdcSampleSemaphore = xSemaphoreCreateBinary();
	if(AdcSampleSemaphore == NULL) {
		return RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_SEMAPHORE_ERROR);
	}
	
	return NO_EXCEPTION;
}

Retcode_T ConnectivityADCAdc_Enable(void)
{
	
	return NO_EXCEPTION;
}

/**
 * Provides read access to the o2 signal.
 */
Retcode_T ConnectivityADCAdc_O2_Read(uint16_t* result)
{
	Retcode_T exception = NO_EXCEPTION;
	exception = AdcCentral_StartSingle(BSP_Adc_GetHandle(), &o2_config);
	if(exception != NO_EXCEPTION) return exception;
	if (pdTRUE != xSemaphoreTake(AdcSampleSemaphore, (TickType_t) pdMS_TO_TICKS(100)))
	{
		exception = RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_TIMEOUT);
	}
	else
	{
		*result = AdcResultBuffer * 2500 / 4096;
	}
	return exception;
	
	return NO_EXCEPTION;
}

/**
 * Provides write access to the o2 signal.
 */
Retcode_T ConnectivityADCAdc_O2_Write(uint16_t* value)
{
	return RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_FAILURE);
	
	return NO_EXCEPTION;
}



