/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-08-01 18:17:36
 */


#include <FreeRTOS.h>
#include <BCDS_Basics.h>
#include <BCDS_CmdProcessor.h>
#include <timers.h>
#include <BCDS_Retcode.h>
#include "MitaTime.h"
#include "MitaExceptions.h"
#include "MitaEvents.h"

static TimerHandle_t timerHandleEvery20Millisecond1;

static void InternalHandleEvery20Millisecond1(TimerHandle_t xTimer)
{
	BCDS_UNUSED(xTimer);
	CmdProcessor_Enqueue(&Mita_EventQueue, HandleEvery20Millisecond1, NULL, 0);
}


Retcode_T SetupTime(void)
{
	
	timerHandleEvery20Millisecond1 = xTimerCreate("timerHandleEvery20Millisecond1", UINT32_C(20), pdTRUE, NULL, InternalHandleEvery20Millisecond1);
	
	if(timerHandleEvery20Millisecond1 == NULL)
	{
		return RETCODE(RETCODE_SEVERITY_ERROR, RETCODE_OUT_OF_RESOURCES);
	}
	
	return NO_EXCEPTION;
}

Retcode_T EnableTime(void)
{
	Retcode_T result = NO_EXCEPTION;

	
	result = EveryHandleEvery20Millisecond1_Enable();
	if(result != NO_EXCEPTION)
	{
		return result;
	}
	
	return NO_EXCEPTION;
}

Retcode_T EveryHandleEvery20Millisecond1_Enable(void)
{
	xTimerStart(timerHandleEvery20Millisecond1, 0);
	
	return NO_EXCEPTION;
}


