/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-08-01 18:17:36
 */


#ifndef MITA_EVENTS_H
#define MITA_EVENTS_H

#include <BCDS_Basics.h>
#include <BCDS_Retcode.h>
#include <BCDS_CmdProcessor.h>


extern CmdProcessor_T Mita_EventQueue;

Retcode_T HandleEvery20Millisecond1(void* userParameter1, uint32_t userParameter2);


#endif
