/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2019-08-01 18:17:36
 */


#ifndef MITA_TIME_H
#define MITA_TIME_H

#include <BCDS_Retcode.h>


Retcode_T SetupTime(void);

Retcode_T EnableTime(void);

Retcode_T EveryHandleEvery20Millisecond1_Enable(void);


#endif
